name: make-docker

on:
  workflow_run:
    workflows: ['Docker App CI']
    types:
      - completed
  workflow_dispatch:

jobs:
  login:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: wikiless

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'Metastem/Wikiless'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ github.ref_name }}/Dockerfile          
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.PACKAGE_NAME }}
          platforms: linux/arm64
